'use strict';

module.exports = {
  DATA_DIR: `./data/`,
  DATA_TITLES_FILE_NAME: `titles.txt`,
  DATA_SENTENCES_FILE_NAME: `sentences.txt`,
  DATA_CATEGORIES_FILE_NAME: `categories.txt`,
  MOCK_FILE_MIN_LIMIT: 1,
  MOCK_FILE_MAX_LIMIT: 1000,
  MOCK_FILE_NAME: `mocks.json`,
  PICTURE_MIN_LIMIT: 1,
  PICTURE_MAX_LIMIT: 16,
  DESCRIPTION_MIN_LIMIT: 0,
  DESCRIPTION_MAX_LIMIT: 5,
  SUM_MIN_LIMIT: 1000,
  SUM_MAX_LIMIT: 10000,
  EXIT_CODE: {
    SUCCESS: 0,
    ERROR: 1
  }
};
